project:
  type: book
  output-dir: docs

book:
  favicon: "./images/geni.png"
  title: "Sclerostin pQTL MR"
  author:
  - name: James Staley
    orcid: 0009-0001-9520-5011
    affiliations:
      - name: UCB Pharma
  date: today
  chapters:
    - index.qmd
  repo-url: https://github.com/jrs95/sclerostin_pqtl_mr
  repo-actions: none

  page-footer:
    left: "[![](https://img.shields.io/badge/Code-GPL--3-BD0000.svg)](https://www.gnu.org/licenses/gpl-3.0.en.html) [![](https://img.shields.io/badge/Data-CC--BY--4.0-00AFD4.svg)](https://creativecommons.org/licenses/by/4.0/)"
    # right: "&copy; CC-BY, 2023"
    right: "James Staley"
    border: true

  sidebar:
    logo: "./images/geni.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1

include-in-header:
  - text: |
      <link rel = "shortcut icon" href = "images/geni_favicon.png" />

format:
  html:
    grid:
      sidebar-width: 275px
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    code-tools: true
    code-link: false
    toc: true
    number-depth: 3

editor: visual